title: Beyond Me.
logo_img: /assets/img/icons/logo.svg
favicon: /assets/favicon.ico
description: 대한민국의 한 컴퓨터공학과 학생이 코딩과 취미 등의 이야기를 하는 공간.
global_tags: computer cs cse computerscience computerengineering korea korean coding student
copyright: © Yunho Jang 2026
timezone: Asia/Seoul

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

comments:
  # Global switch for the post comment system. Keeping it empty means disabled.
  provider: giscus # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: "YunhoJangg/yunhojangg.github.io" # <gh-username>/<repo>
    repo_id: "R_kgDOTywTgw"
    category: "Comments"
    category_id: "DIC_kwDOTywTg84DDGXK"
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: "0" # optional, default to the value of `1`

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
